name: Preparant per producció
run-name: ${{ github.actor }} està pujant l'aplicació a PROD 🚀

on:
  push:
    branches:
      - 'develop'

  pull_request:
    branches:
      - 'develop'
      
jobs:
  Pujar-a-produccio-amb-SCP:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v4
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install npm dependencies for Nuxt.js
        working-directory: ./front/cine-app
        run: npm install
      
      - name: Run build task for Nuxt.js
        working-directory: ./front/cine-app
        run: npm run build --if-present

      - name: Pujant Nuxt.js
        uses: burnett01/rsync-deployments@7.0.0
        with:
          switches: -avzr --delete
          path: front/cine-app/dist/
          remote_path: ${{ secrets.REMOTE_TARGET }}nuxt
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.KEY_SECRET }}  

      - name: Pujant Laravel  
        uses: burnett01/rsync-deployments@7.0.0
        with:
          switches: -avzr 
          path: laravel/
          remote_path: ${{ secrets.REMOTE_TARGET }}laravel
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.KEY_SECRET }} 

      - name: Npm install i composer install a prod
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.KEY_SECRET }}
          command_timeout: 30m
          script: |
            cd ${{ secrets.REMOTE_TARGET }}nuxt && npm install && cd .. && cd ./laravel && composer install

      - run: echo "🍏 This job's status is ${{ job.status }}."