name: Preparant per preproducció
run-name: ${{ github.actor }} està pujant l'aplicació a PRE-PROD  🚀
on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop
jobs:
  Pujar-a-produccio-amb-SCP:
    runs-on: ubuntu-latest
    steps:
      - name: Obtenint el codi del respositori
        uses: actions/checkout@v4

      - name: Crear Dist Nuxt
        run: |
          cd ${{ github.workspace }}/front/cine-app/
          npm install
          npm run build

      - name: scp a produccio
        run: |
          echo "${{ secrets.KEY_SECRET }}" > ~/prod_key.pem
          chmod 600 ~/prod_key.pem
          cd ${{ github.workspace }}/front/cine-app/
          scp -r -o stricthostkeychecking=no -o UserKnownHostsFile=/dev/null -i "~/prod_key.pem" ./nuxt/dist/* ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/a22betvilver/web/pre-tr3-cinemavilla.a22betvilver.daw.inspedralbes.cat/public_html/
      - run: echo "🍏 This job's status is ${{ job.status }}."
